embedded_components {
  id: "collisionobject1"
  type: "collisionobject"
  data: "collision_shape: \"/features/gameplay/3d_level/objects/kenny_holiday_kit/cabin-roof-corner_1.convexshape\"\n"
  "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"geometry\"\n"
  "mask: \"player\"\n"
  "mask: \"enemy\"\n"
  "mask: \"money\"\n"
  "mask: \"geometry\"\n"
  "mask: \"obstacle\"\n"
  "event_collision: false\n"
  "event_contact: false\n"
  "event_trigger: false\n"
  ""
}
embedded_components {
  id: "collisionobject2"
  type: "collisionobject"
  data: "collision_shape: \"/features/gameplay/3d_level/objects/kenny_holiday_kit/cabin-roof-corner_2.convexshape\"\n"
  "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"geometry\"\n"
  "mask: \"player\"\n"
  "mask: \"enemy\"\n"
  "mask: \"money\"\n"
  "mask: \"geometry\"\n"
  "mask: \"obstacle\"\n"
  "event_collision: false\n"
  "event_contact: false\n"
  "event_trigger: false\n"
  ""
}
embedded_components {
  id: "collisionobject3"
  type: "collisionobject"
  data: "collision_shape: \"/features/gameplay/3d_level/objects/kenny_holiday_kit/cabin-roof-corner_3.convexshape\"\n"
  "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"geometry\"\n"
  "mask: \"player\"\n"
  "mask: \"enemy\"\n"
  "mask: \"money\"\n"
  "mask: \"geometry\"\n"
  "mask: \"obstacle\"\n"
  "event_collision: false\n"
  "event_contact: false\n"
  "event_trigger: false\n"
  ""
}
embedded_components {
  id: "collisionobject4"
  type: "collisionobject"
  data: "collision_shape: \"/features/gameplay/3d_level/objects/kenny_holiday_kit/cabin-roof-corner_4.convexshape\"\n"
  "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"geometry\"\n"
  "mask: \"player\"\n"
  "mask: \"enemy\"\n"
  "mask: \"money\"\n"
  "mask: \"geometry\"\n"
  "mask: \"obstacle\"\n"
  "event_collision: false\n"
  "event_contact: false\n"
  "event_trigger: false\n"
  ""
}
embedded_components {
  id: "collisionobject5"
  type: "collisionobject"
  data: "collision_shape: \"/features/gameplay/3d_level/objects/kenny_holiday_kit/cabin-roof-corner_5.convexshape\"\n"
  "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"geometry\"\n"
  "mask: \"player\"\n"
  "mask: \"enemy\"\n"
  "mask: \"money\"\n"
  "mask: \"geometry\"\n"
  "mask: \"obstacle\"\n"
  "event_collision: false\n"
  "event_contact: false\n"
  "event_trigger: false\n"
  ""
}
embedded_components {
  id: "collisionobject6"
  type: "collisionobject"
  data: "collision_shape: \"/features/gameplay/3d_level/objects/kenny_holiday_kit/cabin-roof-corner_6.convexshape\"\n"
  "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"geometry\"\n"
  "mask: \"player\"\n"
  "mask: \"enemy\"\n"
  "mask: \"money\"\n"
  "mask: \"geometry\"\n"
  "mask: \"obstacle\"\n"
  "event_collision: false\n"
  "event_contact: false\n"
  "event_trigger: false\n"
  ""
}
embedded_components {
  id: "collisionobject7"
  type: "collisionobject"
  data: "collision_shape: \"/features/gameplay/3d_level/objects/kenny_holiday_kit/cabin-roof-corner_7.convexshape\"\n"
  "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"geometry\"\n"
  "mask: \"player\"\n"
  "mask: \"enemy\"\n"
  "mask: \"money\"\n"
  "mask: \"geometry\"\n"
  "mask: \"obstacle\"\n"
  "event_collision: false\n"
  "event_contact: false\n"
  "event_trigger: false\n"
  ""
}
embedded_components {
  id: "collisionobject8"
  type: "collisionobject"
  data: "collision_shape: \"/features/gameplay/3d_level/objects/kenny_holiday_kit/cabin-roof-corner_8.convexshape\"\n"
  "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"geometry\"\n"
  "mask: \"player\"\n"
  "mask: \"enemy\"\n"
  "mask: \"money\"\n"
  "mask: \"geometry\"\n"
  "mask: \"obstacle\"\n"
  "event_collision: false\n"
  "event_contact: false\n"
  "event_trigger: false\n"
  ""
}
embedded_components {
  id: "collisionobject9"
  type: "collisionobject"
  data: "collision_shape: \"/features/gameplay/3d_level/objects/kenny_holiday_kit/cabin-roof-corner_9.convexshape\"\n"
  "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"geometry\"\n"
  "mask: \"player\"\n"
  "mask: \"enemy\"\n"
  "mask: \"money\"\n"
  "mask: \"geometry\"\n"
  "mask: \"obstacle\"\n"
  "event_collision: false\n"
  "event_contact: false\n"
  "event_trigger: false\n"
  ""
}
