embedded_components {
  id: "collisionobject1"
  type: "collisionobject"
  data: "collision_shape: \"/features/gameplay/3d_level/objects/kenny_holiday_kit/rocks-medium-collision_01.convexshape\"\n"
  "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"geometry\"\n"
  "mask: \"player, enemy, money, geometry, obstacle\"\n"
  "linear_damping: 0.0\n"
  "angular_damping: 0.0\n"
  "locked_rotation: false\n"
  "bullet: false\n"
  ""
}
embedded_components {
  id: "collisionobject2"
  type: "collisionobject"
  data: "collision_shape: \"/features/gameplay/3d_level/objects/kenny_holiday_kit/rocks-medium-collision_02.convexshape\"\n"
  "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"geometry\"\n"
  "mask: \"player, enemy, money, geometry, obstacle\"\n"
  "linear_damping: 0.0\n"
  "angular_damping: 0.0\n"
  "locked_rotation: false\n"
  "bullet: false\n"
  ""
}
embedded_components {
  id: "collisionobject3"
  type: "collisionobject"
  data: "collision_shape: \"/features/gameplay/3d_level/objects/kenny_holiday_kit/rocks-medium-collision_03.convexshape\"\n"
  "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"geometry\"\n"
  "mask: \"player, enemy, money, geometry, obstacle\"\n"
  "linear_damping: 0.0\n"
  "angular_damping: 0.0\n"
  "locked_rotation: false\n"
  "bullet: false\n"
  ""
}
embedded_components {
  id: "collisionobject4"
  type: "collisionobject"
  data: "collision_shape: \"/features/gameplay/3d_level/objects/kenny_holiday_kit/rocks-medium-collision_04.convexshape\"\n"
  "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"geometry\"\n"
  "mask: \"player, enemy, money, geometry, obstacle\"\n"
  "linear_damping: 0.0\n"
  "angular_damping: 0.0\n"
  "locked_rotation: false\n"
  "bullet: false\n"
  ""
}
embedded_components {
  id: "collisionobject5"
  type: "collisionobject"
  data: "collision_shape: \"/features/gameplay/3d_level/objects/kenny_holiday_kit/rocks-medium-collision_05.convexshape\"\n"
  "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"geometry\"\n"
  "mask: \"player, enemy, money, geometry, obstacle\"\n"
  "linear_damping: 0.0\n"
  "angular_damping: 0.0\n"
  "locked_rotation: false\n"
  "bullet: false\n"
  ""
}
embedded_components {
  id: "collisionobject6"
  type: "collisionobject"
  data: "collision_shape: \"/features/gameplay/3d_level/objects/kenny_holiday_kit/rocks-medium-collision_06.convexshape\"\n"
  "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"geometry\"\n"
  "mask: \"player, enemy, money, geometry, obstacle\"\n"
  "linear_damping: 0.0\n"
  "angular_damping: 0.0\n"
  "locked_rotation: false\n"
  "bullet: false\n"
  ""
}
embedded_components {
  id: "collisionobject7"
  type: "collisionobject"
  data: "collision_shape: \"/features/gameplay/3d_level/objects/kenny_holiday_kit/rocks-medium-collision_07.convexshape\"\n"
  "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"geometry\"\n"
  "mask: \"player, enemy, money, geometry, obstacle\"\n"
  "linear_damping: 0.0\n"
  "angular_damping: 0.0\n"
  "locked_rotation: false\n"
  "bullet: false\n"
  ""
}
embedded_components {
  id: "collisionobject8"
  type: "collisionobject"
  data: "collision_shape: \"/features/gameplay/3d_level/objects/kenny_holiday_kit/rocks-medium-collision_08.convexshape\"\n"
  "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"geometry\"\n"
  "mask: \"player, enemy, money, geometry, obstacle\"\n"
  "linear_damping: 0.0\n"
  "angular_damping: 0.0\n"
  "locked_rotation: false\n"
  "bullet: false\n"
  ""
}
embedded_components {
  id: "collisionobject9"
  type: "collisionobject"
  data: "collision_shape: \"/features/gameplay/3d_level/objects/kenny_holiday_kit/rocks-medium-collision_09.convexshape\"\n"
  "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"geometry\"\n"
  "mask: \"player, enemy, money, geometry, obstacle\"\n"
  "linear_damping: 0.0\n"
  "angular_damping: 0.0\n"
  "locked_rotation: false\n"
  "bullet: false\n"
  ""
}
embedded_components {
  id: "collisionobject10"
  type: "collisionobject"
  data: "collision_shape: \"/features/gameplay/3d_level/objects/kenny_holiday_kit/rocks-medium-collision_10.convexshape\"\n"
  "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"geometry\"\n"
  "mask: \"player, enemy, money, geometry, obstacle\"\n"
  "linear_damping: 0.0\n"
  "angular_damping: 0.0\n"
  "locked_rotation: false\n"
  "bullet: false\n"
  ""
}
embedded_components {
  id: "collisionobject11"
  type: "collisionobject"
  data: "collision_shape: \"/features/gameplay/3d_level/objects/kenny_holiday_kit/rocks-medium-collision_11.convexshape\"\n"
  "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"geometry\"\n"
  "mask: \"player, enemy, money, geometry, obstacle\"\n"
  "linear_damping: 0.0\n"
  "angular_damping: 0.0\n"
  "locked_rotation: false\n"
  "bullet: false\n"
  ""
}
embedded_components {
  id: "collisionobject12"
  type: "collisionobject"
  data: "collision_shape: \"/features/gameplay/3d_level/objects/kenny_holiday_kit/rocks-medium-collision_12.convexshape\"\n"
  "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"geometry\"\n"
  "mask: \"player, enemy, money, geometry, obstacle\"\n"
  "linear_damping: 0.0\n"
  "angular_damping: 0.0\n"
  "locked_rotation: false\n"
  "bullet: false\n"
  ""
}
embedded_components {
  id: "collisionobject13"
  type: "collisionobject"
  data: "collision_shape: \"/features/gameplay/3d_level/objects/kenny_holiday_kit/rocks-medium-collision_13.convexshape\"\n"
  "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"geometry\"\n"
  "mask: \"player, enemy, money, geometry, obstacle\"\n"
  "linear_damping: 0.0\n"
  "angular_damping: 0.0\n"
  "locked_rotation: false\n"
  "bullet: false\n"
  ""
}
embedded_components {
  id: "collisionobject14"
  type: "collisionobject"
  data: "collision_shape: \"/features/gameplay/3d_level/objects/kenny_holiday_kit/rocks-medium-collision_14.convexshape\"\n"
  "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"geometry\"\n"
  "mask: \"player, enemy, money, geometry, obstacle\"\n"
  "linear_damping: 0.0\n"
  "angular_damping: 0.0\n"
  "locked_rotation: false\n"
  "bullet: false\n"
  ""
}
embedded_components {
  id: "collisionobject15"
  type: "collisionobject"
  data: "collision_shape: \"/features/gameplay/3d_level/objects/kenny_holiday_kit/rocks-medium-collision_15.convexshape\"\n"
  "type: COLLISION_OBJECT_TYPE_STATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"geometry\"\n"
  "mask: \"player, enemy, money, geometry, obstacle\"\n"
  "linear_damping: 0.0\n"
  "angular_damping: 0.0\n"
  "locked_rotation: false\n"
  "bullet: false\n"
  ""
}
